### ISSUE TITLE
No route to host

### ISSUE THREAD

**Issue by cloudlena** [cloudnautique/dynamic-drone-nodes#2]
I am running this using the standard Rancher Catalog configuration. However, the dynamic_drones_mgr service keeps failing with the error `Get http://droneserver:8000/api/nodes: dial tcp 10.42.101.120:8000: getsockopt: no route to host`. Is it possible that I'm getting this because the dynamic_drones_mgr and the drone server are running on different hosts?

**Comment by cloudnautique** [comment]
Its ok if they run on separate hosts. It could be that the overlay network is not working as expected. Are you able to jump inside other containers and ping containers on different hosts? That would suggest a broader issue. Each node needs to have 500/UDP and 4500/UDP open to each other in order for the overlay to work.

**Comment by cloudlena** [comment]
Thanks for the quick reply, @cloudnautique! Yes, I can ping other containers if they are part of the same stack. I'm running a couple of stacks with interconnected containers on both hosts and the UDP ports are both open.

**Comment by cloudlena** [comment]
I'm also not getting this issue consistently so it's probably not an issue of this repo. Sometimes it works, sometimes it doesn't...

**Comment by cloudlena** [comment]
@cloudnautique, I am running the Rancher server on a 1GB memory host so it is constantly running out of memory. I think that might be the origin of this issue. I will investigate and if that is true, close the issue.

**Comment by cloudlena** [comment]
@cloudnautique, I can now confirm that it wasn't the Rancher server's memory which caused the issue. I completely tore down that setup and created a new one from scratch with a 2GB Rancher server host and I'm still getting that issue... Can you please let me know what information would be helpful to you to debug?

I'm running Rancher 1.1.0-dev4 with Rancher Server running on a 2GB Digitalocean machine and two hosts running on a 1GB and a 2GB Digitalocean machine. All three VMs are running on CoreOS 1010.5.0.

The drone-server and the dynamic-drone-mgr are running on different hosts and the `docker-compose.yml` file of the stack is the following:

``` yaml
drone-agent:
  labels:
    io.rancher.scheduler.global: 'true'
  tty: true
  image: rancher/socat-docker
  volumes:
  - /var/run/docker.sock:/var/run/docker.sock
  - /var/lib/docker:/var/lib/docker
  stdin_open: true
dynamic-drones-mgr-0:
  environment:
    DRONE_TOKEN: xxxxx
    DRONE_URL: http://droneserver:8000
  external_links:
  - drone/drone-server:droneserver
  labels:
    io.rancher.container.pull_image: always
    io.rancher.scheduler.affinity:container_labe_soft_ne: io.rancher.stack_service.name=$${stack_name}/drone-agent
  tty: true
  entrypoint:
  - /dynamic-drone-nodes
  - /stacks/droneworkers/services/drone-agent
  image: rancher/drone-config:v0.1.0
  stdin_open: true
```
